### ISSUE TITLE
newest version doesnt start

### ISSUE THREAD

**Issue by DampfWaffel** [Matocolotoe/Skript-1.8#12]
hey, i've running a paper 1.8.8 Server and he throw me a error when enabling. So Skript wont work.

```[21:59:53 INFO]: [Skript] Enabling Skript v2.5-beta1
[21:59:53 ERROR]: Error occurred while enabling Skript v2.5-beta1 (Is it up to date?)
java.lang.ExceptionInInitializerError
        at ch.njol.skript.aliases.Aliases.<clinit>(Aliases.java:141) ~[?:?]
        at ch.njol.skript.Skript.onEnable(Skript.java:387) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[PaperSpigot.jar:git-PaperSpigot-"4c7641d"]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:332) [PaperSpigot.jar:git-PaperSpigot-"4c7641d"]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:407) [PaperSpigot.jar:git-PaperSpigot-"4c7641d"]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:359) [PaperSpigot.jar:git-PaperSpigot-"4c7641d"]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:318) [PaperSpigot.jar:git-PaperSpigot-"4c7641d"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:408) [PaperSpigot.jar:git-PaperSpigot-"4c7641d"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:372) [PaperSpigot.jar:git-PaperSpigot-"4c7641d"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:327) [PaperSpigot.jar:git-PaperSpigot-"4c7641d"]
        at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:267) [PaperSpigot.jar:git-PaperSpigot-"4c7641d"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:563) [PaperSpigot.jar:git-PaperSpigot-"4c7641d"]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_241]
Caused by: java.lang.IllegalArgumentException: No enum constant org.bukkit.Material.END_ROD
        at java.lang.Enum.valueOf(Unknown Source) ~[?:1.8.0_241]
        at org.bukkit.Material.valueOf(Material.java:1) ~[PaperSpigot.jar:git-PaperSpigot-"4c7641d"]
        at ch.njol.skript.aliases.MaterialRegistry.load(MaterialRegistry.java:61) ~[?:?]
        at ch.njol.skript.aliases.ItemData.<clinit>(ItemData.java:94) ~[?:?]
        ... 13 more
[21:59:53 INFO]: [Skript] Disabling Skript v2.5-beta1```

**Comment by Matocolotoe** [comment]
Try deleting the `materials.json` file in the Skript folder and restart your server.

**Comment by DampfWaffel** [comment]
works thanks
