### ISSUE TITLE
filter throws error

### ISSUE THREAD

**Issue by DampfWaffel** [Matocolotoe/Skript-1.8#13]
hey, if i use the input filter from Skript its reloading with no error's in the Chat but gives one in the console.
```[17:49:52 ERROR]: #!#!
[17:49:52 ERROR]: #!#! [Skript] Severe Error:
[17:49:52 ERROR]: #!#! Could not load setLore.sk
[17:49:52 ERROR]: #!#!
[17:49:52 ERROR]: #!#! Something went horribly wrong with Skript.
[17:49:52 ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
[17:49:52 ERROR]: #!#! You should report it at https://github.com/SkriptLang/Skript/issues. Please copy paste this report there (or use paste service).
[17:49:52 ERROR]: #!#! This ensures that your issue is noticed and will be fixed as soon as possible.
[17:49:52 ERROR]: #!#! If you believe this is related to this fork in particular (for example if the issue didn't occur
[17:49:52 ERROR]: #!#! with the latest SkriptLang release), please report it here : https://github.com/Matocolotoe/Skript-1.8/issues
[17:49:52 ERROR]: #!#!
[17:49:52 ERROR]: #!#! Stack trace:
[17:49:52 ERROR]: #!#! java.lang.NullPointerException
[17:49:52 ERROR]: #!#!     at ch.njol.skript.expressions.ExprFilter.access$1(ExprFilter.java:115)
[17:49:52 ERROR]: #!#!     at ch.njol.skript.expressions.ExprFilter$ExprInput.init(ExprFilter.java:190)
[17:49:52 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:252)
[17:49:52 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:179)
[17:49:52 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parseSingleExpr(SkriptParser.java:502)
[17:49:52 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parseExpression(SkriptParser.java:840)
[17:49:52 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1569)
[17:49:52 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1565)
[17:49:52 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:224)
[17:49:52 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:179)
[17:49:52 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parseSingleExpr(SkriptParser.java:502)
[17:49:52 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parseExpression(SkriptParser.java:840)
[17:49:52 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1569)
[17:49:52 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1526)
[17:49:52 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:224)
[17:49:52 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:179)
[17:49:52 ERROR]: #!#!     at ch.njol.skript.lang.Statement.parse(Statement.java:59)
[17:49:52 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadItems(ScriptLoader.java:1031)
[17:49:52 ERROR]: #!#!     at ch.njol.skript.command.Commands.loadCommand(Commands.java:487)
[17:49:52 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadScript(ScriptLoader.java:637)
[17:49:52 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.lambda$4(ScriptLoader.java:402)
[17:49:52 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:421)
[17:49:52 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.lambda$3(ScriptLoader.java:338)
[17:49:52 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:371)
[17:49:52 ERROR]: #!#!     at ch.njol.skript.Skript.reloadScripts(Skript.java:967)
[17:49:52 ERROR]: #!#!     at ch.njol.skript.SkriptCommand.onCommand(SkriptCommand.java:166)
[17:49:52 ERROR]: #!#!     at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[17:49:52 ERROR]: #!#!     at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:146)
[17:49:52 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:666)
[17:49:52 ERROR]: #!#!     at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1189)
[17:49:52 ERROR]: #!#!     at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:1001)
[17:49:52 ERROR]: #!#!     at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45)
[17:49:52 ERROR]: #!#!     at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1)
[17:49:52 ERROR]: #!#!     at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13)
[17:49:52 ERROR]: #!#!     at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
[17:49:52 ERROR]: #!#!     at java.util.concurrent.FutureTask.run(Unknown Source)
[17:49:52 ERROR]: #!#!     at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44)
[17:49:52 ERROR]: #!#!     at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:774)
[17:49:52 ERROR]: #!#!     at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378)
[17:49:52 ERROR]: #!#!     at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:713)
[17:49:52 ERROR]: #!#!     at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616)
[17:49:52 ERROR]: #!#!     at java.lang.Thread.run(Unknown Source)
[17:49:52 ERROR]: #!#!
[17:49:52 ERROR]: #!#! Version Information:
[17:49:52 ERROR]: #!#!   Skript: 2.5-beta1 (latest)
[17:49:52 ERROR]: #!#!     Flavor: github-matocolotoe-1.8
[17:49:52 ERROR]: #!#!     Date: 2020-08-03
[17:49:52 ERROR]: #!#!   Bukkit: 1.8.8-R0.1-SNAPSHOT
[17:49:52 ERROR]: #!#!   Minecraft: 1.8.8
[17:49:52 ERROR]: #!#!   Java: 1.8.0_241 (Java HotSpot(TM) 64-Bit Server VM 25.241-b07)
[17:49:52 ERROR]: #!#!   OS: Windows 10 amd64 10.0
[17:49:52 ERROR]: #!#!
[17:49:52 ERROR]: #!#! Server platform: Paper
[17:49:52 ERROR]: #!#!
[17:49:52 ERROR]: #!#! Current node: set all players gamemode to survival where [gamemode of input is creative] (setLore.sk, line 4)
[17:49:52 ERROR]: #!#! Current item: null
[17:49:52 ERROR]: #!#!
[17:49:52 ERROR]: #!#! Thread: Server thread
[17:49:52 ERROR]: #!#!
[17:49:52 ERROR]: #!#! Language: english
[17:49:52 ERROR]: #!#! Link parse mode: DISABLED
[17:49:52 ERROR]: #!#!
[17:49:52 ERROR]: #!#! End of Error.
[17:49:52 ERROR]: #!#!```

**Comment by Matocolotoe** [comment]
Not related to this fork : https://github.com/SkriptLang/Skript/issues/3267
Will be fixed in the next update.
