### ISSUE TITLE
EffTeleport Error

### ISSUE THREAD

**Issue by andrei923** [Matocolotoe/Skript-1.8#16]
```
[00:41:39 ERROR]: Could not pass event PlayerCommandPreprocessEvent to Skript v2.5.3
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[paper.jar:git-PaperSpigot-"4c7641d"]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[paper.jar:git-PaperSpigot-"4c7641d"]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[paper.jar:git-PaperSpigot-"4c7641d"]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:517) [paper.jar:git-PaperSpigot-"4c7641d"]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:502) [paper.jar:git-PaperSpigot-"4c7641d"]
        at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1181) [paper.jar:git-PaperSpigot-"4c7641d"]
        at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:1001) [paper.jar:git-PaperSpigot-"4c7641d"]
        at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45) [paper.jar:git-PaperSpigot-"4c7641d"]
        at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1) [paper.jar:git-PaperSpigot-"4c7641d"]
        at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [paper.jar:git-PaperSpigot-"4c7641d"]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_242]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_242]
        at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [paper.jar:git-PaperSpigot-"4c7641d"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:774) [paper.jar:git-PaperSpigot-"4c7641d"]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378) [paper.jar:git-PaperSpigot-"4c7641d"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:713) [paper.jar:git-PaperSpigot-"4c7641d"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616) [paper.jar:git-PaperSpigot-"4c7641d"]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]
Caused by: java.lang.NoClassDefFoundError: io/papermc/lib/PaperLib
        at ch.njol.skript.effects.EffTeleport.walk(EffTeleport.java:94) ~[?:?]
        at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:88) ~[?:?]
        at ch.njol.skript.lang.Trigger.execute(Trigger.java:56) ~[?:?]
        at ch.njol.skript.lang.function.ScriptFunction.execute(ScriptFunction.java:89) ~[?:?]
        at ch.njol.skript.lang.function.Function.execute(Function.java:135) ~[?:?]
        at ch.njol.skript.lang.function.FunctionReference.execute(FunctionReference.java:265) ~[?:?]
        at ch.njol.skript.lang.function.EffFunctionCall.execute(EffFunctionCall.java:52) ~[?:?]
        at ch.njol.skript.lang.Effect.run(Effect.java:51) ~[?:?]
        at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:60) ~[?:?]
        at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:88) ~[?:?]
        at ch.njol.skript.lang.Trigger.execute(Trigger.java:56) ~[?:?]
        at ch.njol.skript.command.ScriptCommand.execute2(ScriptCommand.java:291) ~[?:?]
        at ch.njol.skript.command.ScriptCommand.execute(ScriptCommand.java:250) ~[?:?]
        at ch.njol.skript.command.Commands.handleCommand(Commands.java:248) ~[?:?]
        at ch.njol.skript.command.Commands$1.onPlayerCommand(Commands.java:165) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_242]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_242]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_242]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_242]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:300) ~[paper.jar:git-PaperSpigot-"4c7641d"]
        ... 17 more
Caused by: java.lang.ClassNotFoundException: io.papermc.lib.PaperLib
        at java.net.URLClassLoader.findClass(URLClassLoader.java:382) ~[?:1.8.0_242]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:102) ~[paper.jar:git-PaperSpigot-"4c7641d"]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:87) ~[paper.jar:git-PaperSpigot-"4c7641d"]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:419) ~[?:1.8.0_242]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:352) ~[?:1.8.0_242]
        at ch.njol.skript.effects.EffTeleport.walk(EffTeleport.java:94) ~[?:?]
        at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:88) ~[?:?]
        at ch.njol.skript.lang.Trigger.execute(Trigger.java:56) ~[?:?]
        at ch.njol.skript.lang.function.ScriptFunction.execute(ScriptFunction.java:89) ~[?:?]
        at ch.njol.skript.lang.function.Function.execute(Function.java:135) ~[?:?]
        at ch.njol.skript.lang.function.FunctionReference.execute(FunctionReference.java:265) ~[?:?]
        at ch.njol.skript.lang.function.EffFunctionCall.execute(EffFunctionCall.java:52) ~[?:?]
        at ch.njol.skript.lang.Effect.run(Effect.java:51) ~[?:?]
        at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:60) ~[?:?]
        at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:88) ~[?:?]
        at ch.njol.skript.lang.Trigger.execute(Trigger.java:56) ~[?:?]
        at ch.njol.skript.command.ScriptCommand.execute2(ScriptCommand.java:291) ~[?:?]
        at ch.njol.skript.command.ScriptCommand.execute(ScriptCommand.java:250) ~[?:?]
        at ch.njol.skript.command.Commands.handleCommand(Commands.java:248) ~[?:?]
        at ch.njol.skript.command.Commands$1.onPlayerCommand(Commands.java:165) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_242]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_242]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_242]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_242]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:300) ~[paper.jar:git-PaperSpigot-"4c7641d"]
        ... 17 more
>
```
Paperspigot 1.8.8

Probably due to this https://github.com/SkriptLang/Skript/pull/3478

using the old EffTeleport should probably do the job.

**Comment by Matocolotoe** [comment]
Already fixed locally, will upload fixes tomorrow

**Comment by Matocolotoe** [comment]
Since actions are currently not working, here is a [patched version](https://cdn.discordapp.com/attachments/709063765588443206/791052512584400926/Skript.jar) which should fix the problem.
