### ISSUE TITLE
Big error by the skript

### ISSUE THREAD

**Issue by TheGunTerminator** [Matocolotoe/Skript-1.8#20]
Description
So I wanted to update my previous skript (still using 1.8), but when I uploaded the skript 2.5.3 it gave me a huge error

Steps to Reproduce
Just uploaded the .jar file to my plugin folder and then after the restart this happend

Errors / Screenshots

```
[22:15:55 ERROR]: #!#! 
[22:15:55 ERROR]: #!#! [Skript] Severe Error: 
[22:15:55 ERROR]: #!#! Skript's class ch.njol.skript.expressions.ExprSpawnerType generated an exception while loading 
[22:15:55 ERROR]: #!#! 
[22:15:55 ERROR]: #!#! Something went horribly wrong with Skript. 
[22:15:55 ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either. 
[22:15:55 ERROR]: #!#! It looks like you are using some plugin(s) that alter how Skript works (addons). 
[22:15:55 ERROR]: #!#! Here is full list of them: 
[22:15:55 ERROR]: #!#! Factions v1.6.9.5-2.6.2-STABLE 
[22:15:55 ERROR]: #!#! We could not identify which of those are specially related, so this might also be Skript issue. 
[22:15:55 ERROR]: #!#! You should try disabling those plugins one by one, trying to find which one causes it. 
[22:15:55 ERROR]: #!#! If the error doesn't disappear even after disabling all listed plugins, it is probably Skript issue. 
[22:15:55 ERROR]: #!#! In that case, you will be given instruction on how should you report it. 
[22:15:55 ERROR]: #!#! On the other hand, if the error disappears when disabling some plugin, report it to author of that plugin. 
[22:15:55 ERROR]: #!#! Only if the author tells you to do so, report it to Skript's issue tracker. 
[22:15:55 ERROR]: #!#! 
[22:15:55 ERROR]: #!#! Stack trace: 
[22:15:55 ERROR]: #!#! java.lang.IndexOutOfBoundsException: Index: 0, Size: 0 
[22:15:55 ERROR]: #!#! at java.util.ArrayList.rangeCheck(Unknown Source) 
[22:15:55 ERROR]: #!#! at java.util.ArrayList.get(Unknown Source) 
[22:15:55 ERROR]: #!#! at ch.njol.skript.aliases.ItemType.getMaterial(ItemType.java:1243) 
[22:15:55 ERROR]: #!#! at ch.njol.skript.expressions.ExprSpawnerType.<clinit>(ExprSpawnerType.java:49) 
[22:15:55 ERROR]: #!#! at java.lang.Class.forName0(Native Method) 
[22:15:55 ERROR]: #!#! at java.lang.Class.forName(Unknown Source) 
[22:15:55 ERROR]: #!#! at ch.njol.skript.SkriptAddon.loadClasses(SkriptAddon.java:107) 
[22:15:55 ERROR]: #!#! at ch.njol.skript.Skript.onEnable(Skript.java:435) 
[22:15:55 ERROR]: #!#! at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) 
[22:15:55 ERROR]: #!#! at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:339) 
[22:15:55 ERROR]: #!#! at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:411) 
[22:15:55 ERROR]: #!#! at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:352) 
[22:15:55 ERROR]: #!#! at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:311) 
[22:15:55 ERROR]: #!#! at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:428) 
[22:15:55 ERROR]: #!#! at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:392) 
[22:15:55 ERROR]: #!#! at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:347) 
[22:15:55 ERROR]: #!#! at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:276) 
[22:15:55 ERROR]: #!#! at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:594) 
[22:15:55 ERROR]: #!#! at java.lang.Thread.run(Unknown Source) 
[22:15:55 ERROR]: #!#! 
[22:15:55 ERROR]: #!#! Version Information: 
[22:15:55 ERROR]: #!#! Skript: 2.5.3 (latest) 
[22:15:55 ERROR]: #!#! Flavor: github-matocolotoe-1.8 
[22:15:55 ERROR]: #!#! Date: 2020-12-22 
[22:15:55 ERROR]: #!#! Bukkit: 1.8.8-R0.2-SNAPSHOT 
[22:15:55 ERROR]: #!#! Minecraft: 1.8.8 
[22:15:55 ERROR]: #!#! Java: 1.8.0_261 (Java HotSpot(TM) Client VM 25.261-b12) 
[22:15:55 ERROR]: #!#! OS: Windows 10 x86 10.0 
[22:15:55 ERROR]: #!#! 
[22:15:55 ERROR]: #!#! Server platform: Paper 
[22:15:55 ERROR]: #!#! 
[22:15:55 ERROR]: #!#! Current node: splash potions: (brewing.sk, line 51) 
[22:15:55 ERROR]: #!#! Current item: null 
[22:15:55 ERROR]: #!#! 
[22:15:55 ERROR]: #!#! Thread: Server thread 
[22:15:55 ERROR]: #!#! 
[22:15:55 ERROR]: #!#! Language: english 
[22:15:55 ERROR]: #!#! Link parse mode: DISABLED 
[22:15:55 ERROR]: #!#! 
[22:15:55 ERROR]: #!#! End of Error. 
[22:15:55 ERROR]: #!#!
```

Plugin folder:
![Untitled](https://user-images.githubusercontent.com/78177948/106267977-bb922e00-622a-11eb-88c0-495bbb53790e.png)

**Comment by TheGunTerminator** [comment]
So I deleted the saber plugin, cus the skript said it was by saberfactions

```
[15:19:59 INFO]: [Skript] Enabling Skript v2.5.3
[15:19:59 WARN]: [Skript] You are currently using 32-bit Java. This may result in a StackOverflowError when loading aliases.
[15:19:59 WARN]: [Skript] Please update to 64-bit Java to remove this warning.
[15:19:59 ERROR]: [Skript]  (brewing.sk, line 51: splash potions:')
[15:19:59 ERROR]: [Skript] There was a StackOverflowError that occured while loading aliases. (brewing.sk, line 51: splash potions:')
[15:19:59 ERROR]: [Skript] As you are currently using 32-bit Java, please update to 64-bit Java to resolve the error. (brewing.sk, line 51: splash potions:')
[15:19:59 ERROR]: [Skript] Please report this issue to our GitHub only if updating to 64-bit Java does not fix the issue. (brewing.sk, line 51: splash potions:')
[15:19:59 ERROR]: [Skript]  (brewing.sk, line 51: splash potions:')
[15:20:00 INFO]: [Skript] You're currently running the latest stable version of Skript.
[15:20:00 ERROR]: #!#!
[15:20:00 ERROR]: #!#! [Skript] Severe Error:
[15:20:00 ERROR]: #!#! Skript's class ch.njol.skript.expressions.ExprSpawnerType generated an exception while loading
[15:20:00 ERROR]: #!#!
[15:20:00 ERROR]: #!#! Something went horribly wrong with Skript.
[15:20:00 ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
[15:20:00 ERROR]: #!#! You should report it at https://github.com/SkriptLang/Skript/issues. Please copy paste this report there (or use paste service).
[15:20:00 ERROR]: #!#! This ensures that your issue is noticed and will be fixed as soon as possible.
[15:20:00 ERROR]: #!#! If you believe this is related to this fork in particular (for example if the issue didn't occur
[15:20:00 ERROR]: #!#! with the latest SkriptLang release), please report it here : https://github.com/Matocolotoe/Skript-1.8/issues
[15:20:00 ERROR]: #!#!
[15:20:00 ERROR]: #!#! Stack trace:
[15:20:00 ERROR]: #!#! java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
[15:20:00 ERROR]: #!#!     at java.util.ArrayList.rangeCheck(Unknown Source)
[15:20:00 ERROR]: #!#!     at java.util.ArrayList.get(Unknown Source)
[15:20:00 ERROR]: #!#!     at ch.njol.skript.aliases.ItemType.getMaterial(ItemType.java:1243)
[15:20:00 ERROR]: #!#!     at ch.njol.skript.expressions.ExprSpawnerType.<clinit>(ExprSpawnerType.java:49)
[15:20:00 ERROR]: #!#!     at java.lang.Class.forName0(Native Method)
[15:20:00 ERROR]: #!#!     at java.lang.Class.forName(Unknown Source)
[15:20:00 ERROR]: #!#!     at ch.njol.skript.SkriptAddon.loadClasses(SkriptAddon.java:107)
[15:20:00 ERROR]: #!#!     at ch.njol.skript.Skript.onEnable(Skript.java:435)
[15:20:00 ERROR]: #!#!     at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321)
[15:20:00 ERROR]: #!#!     at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:339)
[15:20:00 ERROR]: #!#!     at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:411)
[15:20:00 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:352)
[15:20:00 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:311)
[15:20:00 ERROR]: #!#!     at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:428)
[15:20:00 ERROR]: #!#!     at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:392)
[15:20:00 ERROR]: #!#!     at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:347)
[15:20:00 ERROR]: #!#!     at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:276)
[15:20:00 ERROR]: #!#!     at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:594)
[15:20:00 ERROR]: #!#!     at java.lang.Thread.run(Unknown Source)
[15:20:00 ERROR]: #!#!
[15:20:00 ERROR]: #!#! Version Information:
[15:20:00 ERROR]: #!#!   Skript: 2.5.3 (latest)
[15:20:00 ERROR]: #!#!     Flavor: github-matocolotoe-1.8
[15:20:00 ERROR]: #!#!     Date: 2020-12-22
[15:20:00 ERROR]: #!#!   Bukkit: 1.8.8-R0.2-SNAPSHOT
[15:20:00 ERROR]: #!#!   Minecraft: 1.8.8
[15:20:00 ERROR]: #!#!   Java: 1.8.0_261 (Java HotSpot(TM) Client VM 25.261-b12)
[15:20:00 ERROR]: #!#!   OS: Windows 10 x86 10.0
[15:20:00 ERROR]: #!#!
[15:20:00 ERROR]: #!#! Server platform: Paper
[15:20:00 ERROR]: #!#!
[15:20:00 ERROR]: #!#! Current node: splash potions: (brewing.sk, line 51)
[15:20:00 ERROR]: #!#! Current item: null
[15:20:00 ERROR]: #!#!
[15:20:00 ERROR]: #!#! Thread: Server thread
[15:20:00 ERROR]: #!#!
[15:20:00 ERROR]: #!#! Language: english
[15:20:00 ERROR]: #!#! Link parse mode: DISABLED
[15:20:00 ERROR]: #!#!
[15:20:00 ERROR]: #!#! End of Error.
[15:20:00 ERROR]: #!#!
```

**Comment by Matocolotoe** [comment]
If you are using 32-bit Java, as the stacktrace explains, you should switch to 64-bit Java, it might solve the problem.

**Comment by kill05** [comment]
sorry to bump a closed issue, but try using spigot instead of bukkit.
