### ISSUE TITLE
CraftMetaLeatherArmor - Unbreakable leather armor error

### ISSUE THREAD

**Issue by raphael950** [Matocolotoe/Skript-1.8#21]
[01:41:08 WARN]: java.lang.NoSuchMethodException: org.bukkit.craftbukkit.v1_8_R3.inventory.CraftMetaLeatherArmor.spigot()
[01:41:08 WARN]:        at java.lang.Class.newNoSuchMethodException(Class.java:567)
[01:41:08 WARN]:        at java.lang.Class.throwExceptionOrReturnNull(Class.java:1222)
[01:41:08 WARN]:        at java.lang.Class.getMethodHelper(Class.java:1308)
[01:41:08 WARN]:        at java.lang.Class.getDeclaredMethod(Class.java:936)
[01:41:08 WARN]:        at ch.njol.skript.expressions.ExprUnbreakable.lambda$0(ExprUnbreakable.java:65)
[01:41:08 WARN]:        at ch.njol.skript.expressions.ExprUnbreakable$$Lambda$871/0x00000000b66689e0.convert(Unknown Source)
[01:41:08 WARN]:        at ch.njol.skript.registrations.Converters.convert(Converters.java:390)
[01:41:08 WARN]:        at ch.njol.skript.registrations.Converters.convertUnsafe(Converters.java:381)
[01:41:08 WARN]:        at ch.njol.skript.expressions.base.PropertyExpression.get(PropertyExpression.java:102)
[01:41:08 WARN]:        at ch.njol.skript.expressions.ExprUnbreakable.get(ExprUnbreakable.java:60)
[01:41:08 WARN]:        at ch.njol.skript.expressions.ExprUnbreakable.get(ExprUnbreakable.java:1)
[01:41:08 WARN]:        at ch.njol.skript.expressions.base.PropertyExpression.get(PropertyExpression.java:73)
[01:41:08 WARN]:        at ch.njol.skript.lang.util.SimpleExpression.getArray(SimpleExpression.java:100)
[01:41:08 WARN]:        at ch.njol.skript.effects.EffChange.execute(EffChange.java:276)
[01:41:08 WARN]:        at ch.njol.skript.lang.Effect.run(Effect.java:51)
[01:41:08 WARN]:        at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:60)
[01:41:08 WARN]:        at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:88)
[01:41:08 WARN]:        at ch.njol.skript.lang.Trigger.execute(Trigger.java:56)
[01:41:08 WARN]:        at ch.njol.skript.SkriptEventHandler.check(SkriptEventHandler.java:153)
[01:41:08 WARN]:        at ch.njol.skript.SkriptEventHandler$1.execute(SkriptEventHandler.java:111)
[01:41:08 WARN]:        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78)
[01:41:08 WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[01:41:08 WARN]:        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:517)
[01:41:08 WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:502)
[01:41:08 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:228)
[01:41:08 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:195)
[01:41:08 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:191)
[01:41:08 WARN]:        at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:721)
[01:41:08 WARN]:        at net.minecraft.server.v1_8_R3.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:52)
[01:41:08 WARN]:        at net.minecraft.server.v1_8_R3.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:1)
[01:41:08 WARN]:        at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13)
[01:41:08 WARN]:        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[01:41:08 WARN]:        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[01:41:08 WARN]:        at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44)
[01:41:08 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:774)
[01:41:08 WARN]:        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378)
[01:41:08 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:713)
[01:41:08 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616)
[01:41:08 WARN]:        at java.lang.Thread.run(Thread.java:823)

code on my script:
not working: set player's helmet to unbreakable leather helmet of protection 2
working: set player's chestplate to unbreakable diamond chestplate of protection 2

**Comment by Matocolotoe** [comment]
Seems like ExprUnbreakable needs more fixes.
