### ISSUE TITLE
Error PlayerInteractEvent

### ISSUE THREAD

**Issue by andrei923** [Matocolotoe/Skript-1.8#23]
```
> [11:40:50 ERROR]: Could not pass event PlayerInteractEvent to Skript v2.5.3
java.lang.NoClassDefFoundError: org/bukkit/block/data/type/Bed$Part
at java.lang.Class.getDeclaredMethods0(Native Method) ~[?:1.8.0_275]
at java.lang.Class.privateGetDeclaredMethods(Class.java:2701) ~[?:1.8.0_275]
at java.lang.Class.getDeclaredMethods(Class.java:1975) ~[?:1.8.0_275]
at com.leaf.skriptmirror.util.JavaUtil.methods(JavaUtil.java:54) ~[?:?]
at com.leaf.skriptmirror.skript.reflect.ExprJavaCall.createCallSite(ExprJavaCall.java:382) ~[?:?]
at java.util.HashMap.computeIfAbsent(HashMap.java:1127) ~[?:1.8.0_275]
at com.leaf.skriptmirror.skript.reflect.ExprJavaCall.getCallSite(ExprJavaCall.java:343) ~[?:?]
at com.leaf.skriptmirror.skript.reflect.ExprJavaCall.findCompatibleMethod(ExprJavaCall.java:521) ~[?:?]
at com.leaf.skriptmirror.skript.reflect.ExprJavaCall.invoke(ExprJavaCall.java:432) ~[?:?]
at com.leaf.skriptmirror.skript.reflect.ExprJavaCall.getSingle(ExprJavaCall.java:137) ~[?:?]
at com.leaf.skriptmirror.skript.CondExpressionStatement.check(CondExpressionStatement.java:40) ~[?:?]
at ch.njol.skript.lang.Condition.run(Condition.java:55) ~[?:?]
at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:60) ~[?:?]
at com.leaf.skriptmirror.skript.CondExpressionStatement.walk(CondExpressionStatement.java:66) ~[?:?]
at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:88) ~[?:?]
at ch.njol.skript.lang.Trigger.execute(Trigger.java:56) ~[?:?]
at ch.njol.skript.SkriptEventHandler.check(SkriptEventHandler.java:153) ~[?:?]
at ch.njol.skript.SkriptEventHandler$1.execute(SkriptEventHandler.java:111) ~[?:?]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[server.jar:git-PaperSpigot-"4c7641d"]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[server.jar:git-PaperSpigot-"4c7641d"]
at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:517) [server.jar:git-PaperSpigot-"4c7641d"]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:502) [server.jar:git-PaperSpigot-"4c7641d"]
at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:228) [server.jar:git-PaperSpigot-"4c7641d"]
at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:195) [server.jar:git-PaperSpigot-"4c7641d"]
at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:191) [server.jar:git-PaperSpigot-"4c7641d"]
at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:721) [server.jar:git-PaperSpigot-"4c7641d"]
at net.minecraft.server.v1_8_R3.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:52) [server.jar:git-PaperSpigot-"4c7641d"]
at net.minecraft.server.v1_8_R3.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:1) [server.jar:git-PaperSpigot-"4c7641d"]
at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [server.jar:git-PaperSpigot-"4c7641d"]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_275]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_275]
at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [server.jar:git-PaperSpigot-"4c7641d"]
at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:774) [server.jar:git-PaperSpigot-"4c7641d"]
at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378) [server.jar:git-PaperSpigot-"4c7641d"]
at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:713) [server.jar:git-PaperSpigot-"4c7641d"]
at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616) [server.jar:git-PaperSpigot-"4c7641d"]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_275]
Caused by: java.lang.ClassNotFoundException: org.bukkit.block.data.type.Bed$Part
at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:92) ~[server.jar:git-PaperSpigot-"4c7641d"]
at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:87) ~[server.jar:git-PaperSpigot-"4c7641d"]
at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[?:1.8.0_275]
at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_275]
... 37 more
```

**Comment by TPGamesNL** [comment]
You have a `on place` trigger somewhere, with a skript-mirror call in a condition. Can you send that code?

**Comment by andrei923** [comment]
my bad was due to skript mirror.
