### ISSUE TITLE
Error while starting.

### ISSUE THREAD

**Issue by celeneous** [Matocolotoe/Skript-1.8#30]
```
Error occurred while enabling Skript v2.5.1 (Is it up to date?)
java.lang.NoClassDefFoundError: com/google/gson/GsonBuilder
    at ch.njol.skript.update.ReleaseManifest.load(ReleaseManifest.java:48) ~[?:?]
    at ch.njol.skript.SkriptUpdater.loadManifest(SkriptUpdater.java:75) ~[?:?]
    at ch.njol.skript.SkriptUpdater.<init>(SkriptUpdater.java:58) ~[?:?]
    at ch.njol.skript.Skript.onEnable(Skript.java:314) ~[?:?]
    at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[server.jar:git-Spigot-c3c767f-33d5de3]
    at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:335) [server.jar:git-Spigot-c3c767f-33d5de3]
    at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [server.jar:git-Spigot-c3c767f-33d5de3]
    at org.bukkit.craftbukkit.v1_8_R1.CraftServer.loadPlugin(CraftServer.java:356) [server.jar:git-Spigot-c3c767f-33d5de3]
    at org.bukkit.craftbukkit.v1_8_R1.CraftServer.enablePlugins(CraftServer.java:316) [server.jar:git-Spigot-c3c767f-33d5de3]
    at net.minecraft.server.v1_8_R1.MinecraftServer.q(MinecraftServer.java:402) [server.jar:git-Spigot-c3c767f-33d5de3]
    at net.minecraft.server.v1_8_R1.MinecraftServer.k(MinecraftServer.java:370) [server.jar:git-Spigot-c3c767f-33d5de3]
    at net.minecraft.server.v1_8_R1.MinecraftServer.a(MinecraftServer.java:325) [server.jar:git-Spigot-c3c767f-33d5de3]
    at net.minecraft.server.v1_8_R1.DedicatedServer.init(DedicatedServer.java:211) [server.jar:git-Spigot-c3c767f-33d5de3]
    at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:505) [server.jar:git-Spigot-c3c767f-33d5de3]
    at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
Caused by: java.lang.ClassNotFoundException: com.google.gson.GsonBuilder
    at java.net.URLClassLoader.findClass(URLClassLoader.java:382) ~[?:1.8.0_212]
    at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101) ~[server.jar:git-Spigot-c3c767f-33d5de3]
    at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[server.jar:git-Spigot-c3c767f-33d5de3]
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_212]
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_212]
    ... 15 more
```

I'm using spigot 1.8, and no other plugins. Please help!

**Comment by celeneous** [comment]
The host I use doesn't have paper 1.8*****

**Comment by Matocolotoe** [comment]
Does this still happen with the latest version (i.e. 2.5.3) ?

**Comment by celeneous** [comment]
> Does this still happen with the latest version (i.e. 2.5.3) ?

Yup!
```
Error occurred while enabling Skript v2.5.3 (Is it up to date?)
java.lang.NoClassDefFoundError: com/google/gson/GsonBuilder
    at ch.njol.skript.update.ReleaseManifest.load(ReleaseManifest.java:48) ~[?:?]
    at ch.njol.skript.SkriptUpdater.loadManifest(SkriptUpdater.java:75) ~[?:?]
    at ch.njol.skript.SkriptUpdater.<init>(SkriptUpdater.java:58) ~[?:?]
    at ch.njol.skript.Skript.onEnable(Skript.java:306) ~[?:?]
    at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[server.jar:git-Spigot-c3c767f-33d5de3]
    at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:335) [server.jar:git-Spigot-c3c767f-33d5de3]
    at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [server.jar:git-Spigot-c3c767f-33d5de3]
    at org.bukkit.craftbukkit.v1_8_R1.CraftServer.loadPlugin(CraftServer.java:356) [server.jar:git-Spigot-c3c767f-33d5de3]
    at org.bukkit.craftbukkit.v1_8_R1.CraftServer.enablePlugins(CraftServer.java:316) [server.jar:git-Spigot-c3c767f-33d5de3]
    at net.minecraft.server.v1_8_R1.MinecraftServer.q(MinecraftServer.java:402) [server.jar:git-Spigot-c3c767f-33d5de3]
    at net.minecraft.server.v1_8_R1.MinecraftServer.k(MinecraftServer.java:370) [server.jar:git-Spigot-c3c767f-33d5de3]
    at net.minecraft.server.v1_8_R1.MinecraftServer.a(MinecraftServer.java:325) [server.jar:git-Spigot-c3c767f-33d5de3]
    at net.minecraft.server.v1_8_R1.DedicatedServer.init(DedicatedServer.java:211) [server.jar:git-Spigot-c3c767f-33d5de3]
    at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:505) [server.jar:git-Spigot-c3c767f-33d5de3]
    at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
Caused by: java.lang.ClassNotFoundException: com.google.gson.GsonBuilder
    at java.net.URLClassLoader.findClass(URLClassLoader.java:382) ~[?:1.8.0_212]
    at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101) ~[server.jar:git-Spigot-c3c767f-33d5de3]
    at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[server.jar:git-Spigot-c3c767f-33d5de3]
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_212]
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_212]
    ... 15 more
```

**Comment by celeneous** [comment]
Sorry for taking so long to reply, I Had to install the newest version (2.5.3)

**Comment by Matocolotoe** [comment]
Are you using the latest version of Spigot 1.8 ? Because Gson should be included in it

**Comment by celeneous** [comment]
> Are you using the latest version of Spigot 1.8 ? Because Gson should be included in it

![image](https://user-images.githubusercontent.com/66046567/112763138-2bc1f380-8fd1-11eb-9589-fdd1a2279e55.png)

**Comment by celeneous** [comment]
> Are you using the latest version of Spigot 1.8 ? Because Gson should be included in it

It doesn't say

**Comment by celeneous** [comment]
![image](https://user-images.githubusercontent.com/66046567/112775705-aad41d80-900b-11eb-83d3-6508686ce4cd.png)

**Comment by Matocolotoe** [comment]
Does it still occur with Spigot 1.8.**8** ?

**Comment by celeneous** [comment]
I was using spigot 1.8.8, yes that's the problem I'm having

> Does it still occur with Spigot 1.8.**8** ?

**Comment by Matocolotoe** [comment]
`MC: 1.8` means this is Spigot 1.8.0 iirc

**Comment by celeneous** [comment]
> `MC: 1.8` means this is Spigot 1.8.0 iirc

whoops lmao, yeah. That's the only 1.8 version that this host uses :/

**Comment by Matocolotoe** [comment]
Well I believe that's the only way to fix it
