### ISSUE TITLE
[Skript] Erreur grave

### ISSUE THREAD

**Issue by STEED01** [Matocolotoe/Skript-1.8#33]
### Description
My skript was not loaded.
### Steps to Reproduce
I don't know how it happened ...

### Expected Behavior
it should have happened that my skript fully loads with an end message.

### Errors / Screenshots
https://cdn.discordapp.com/attachments/364108392022933506/840810010509574204/unknown.png

### Server Information
* **Server version/platform:** 1.8.8
* **Skript version:** 2.2-dev25

### Additional Context
nothing

**Comment by Matocolotoe** [comment]
> Skript version: 2.2-dev25

When [someone suggests you this fork](https://github.com/SkriptLang/Skript/issues/3965#issuecomment-835702204), at least *download it* before posting an issue about it.

**Comment by STEED01** [comment]
Bon.. c'est plus simple de parler en français vu votre position dans votre statut. En gros, si je le reposte ici c'Est que là où je l'ai posté, de 1: c'était pas le bon support. Ensuite, je le poste ici vu que c'est la 1.8 et pour finir, si je le reposte c'est que j'ai fait les manipulation et qu'il bogue tjr...

Donc je cherche encore des solution autre que sur le github pour avoir un maximum d'aide venant de partout et de trouver enfin la bonne solution à mon problème qui dure depuis 3 jours...

**Comment by Matocolotoe** [comment]
> Ensuite, je le poste ici vu que c'est la 1.8

Ce n'est pas exactement ça, ici c'est la dernière version de Skript *ajustée pour la 1.8*, donc aucun support pour les versions antérieures.

> si je le reposte c'est que j'ai fait les manipulation et qu'il bogue tjr...

Quelles manipulations exactement ? De plus vous avez toujours la 2.2-dev25 d'après le screen.

**Comment by STEED01** [comment]
J'ai toujours la 2.2-dev25 car une multitude de personnes me disent de prendre cette version pour mon serveur 1.8.8. Et quand j'avais la 2.5.3 ou la .2, elle boguée aussi. Du coup je ne sais plus quoi faire.

Les manipulations: Save les fichiers .sk, delete le fichier Skript de mon serveur,relancer mon serveur, stopper mon serveur, remettre les fichiers .sk, relancer mon serveur et voir si ça marche à nouveau.. résultat: toujours la même erreur.

**Comment by Matocolotoe** [comment]
> J'ai toujours la 2.2-dev25 car une multitude de personnes me disent de prendre cette version pour mon serveur 1.8.8.
Et quand j'avais la 2.5.3 ou la .2, elle boguée aussi. Du coup je ne sais plus quoi faire.

C'est normal, vous aviez la dernière version de SkriptLang, qui ne supporte que la 1.9+.
Dans ce cas essayez de télécharger Skript-1.8 ([ici](https://github.com/Matocolotoe/Skript-1.8/releases)).

> Les manipulations: Save les fichiers .sk, delete le fichier Skript de mon serveur,relancer mon serveur, stopper mon serveur, remettre les fichiers .sk, relancer mon serveur et voir si ça marche à nouveau.. résultat: toujours la même erreur.

En même temps sans le plugin concerné ça ne risque pas de marcher

**Comment by STEED01** [comment]
Voilà ce que j'ai en changeant la version de Skript:

> [12:03:19 INFO]: CheaterO_o issued server command: /sk reload all
[12:03:21 ERROR]: #!#!
[12:03:21 ERROR]: #!#! [Skript] Severe Error:
[12:03:21 ERROR]: #!#! Could not load A--Bugs--A.sk
[12:03:21 ERROR]: #!#!     at ch.njol.skript.registrations.Classes.getClassInfo(Classes.java:262)
[12:03:21 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.createExprInfo(SkriptParser.java:1837)
[12:03:21 ERROR]: #!#!     at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45)
[12:03:21 ERROR]: #!#!     at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1)
[12:03:21 ERROR]: #!#!     at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13)
[12:03:21 ERROR]: #!#!     at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
[12:03:21 ERROR]: #!#!     at java.util.concurrent.FutureTask.run(Unknown Source)
[12:03:21 ERROR]: #!#!     at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44)
[12:03:21 ERROR]: #!#!     at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:715)
[12:03:21 ERROR]: #!#!     at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374)
[12:03:21 ERROR]: #!#!     at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654)
[12:03:21 ERROR]: #!#!     at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557)
[12:03:21 ERROR]: #!#!     at java.lang.Thread.run(Unknown Source)
[12:03:21 ERROR]: #!#!
[12:03:21 ERROR]: #!#! Version Information:
[12:03:21 ERROR]: #!#!   Skript: 2.5.3 (latest)
[12:03:21 ERROR]: #!#!     Flavor: github-matocolotoe-1.8
[12:03:21 ERROR]: #!#!     Date: 2020-12-22
[12:03:21 ERROR]: #!#!   Bukkit: 1.8.8-R0.1-SNAPSHOT
[12:03:21 ERROR]: #!#!   Minecraft: 1.8.8
[12:03:21 ERROR]: #!#!   Java: 1.8.0_281 (Java HotSpot(TM) 64-Bit Server VM 25.281-b09)
[12:03:21 ERROR]: #!#!   OS: Windows 10 amd64 10.0
[12:03:21 ERROR]: #!#!
[12:03:21 ERROR]: #!#! Server platform: Spigot
[12:03:21 ERROR]: #!#!
[12:03:21 ERROR]: #!#! Current node: loop all players: (scoreboard.sk, line 4)
[12:03:21 ERROR]: #!#! Current item: null
[12:03:21 ERROR]: #!#!
[12:03:21 ERROR]: #!#! Thread: Server thread
[12:03:21 ERROR]: #!#!
[12:03:21 ERROR]: #!#! Language: english
[12:03:21 ERROR]: #!#! Link parse mode: DISABLED
[12:03:21 ERROR]: #!#!
[12:03:21 ERROR]: #!#! End of Error.
[12:03:21 ERROR]: #!#!
[12:03:21 ERROR]: #!#!
[12:03:21 ERROR]: #!#! [Skript] Severe Error:
[12:03:21 ERROR]: #!#! Could not load tchat.sk
[12:03:21 ERROR]: #!#!
[12:03:21 ERROR]: #!#! Something went horribly wrong with Skript.
[12:03:21 ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
[12:03:21 ERROR]: #!#! It looks like you are using some plugin(s) that alter how Skript works (addons).
[12:03:21 ERROR]: #!#! Here is full list of them:
[12:03:21 ERROR]: #!#! skRayFall v1.9.10 (http://sk.rayfall.net/) skLib v1.1.0 (https://github.com/WheezyGold7931/skLib/) TuSKe v1.8.2 (github.com/Tuke-Nuke/TuSKe) skUtilities v0.9.2 (https://tim740.github.io/) WildSkript v1.8 (http://www.dzikoysk.net/) SkQuery v4.1.3 Skellett v1.9.8 (https://forums.skunity.com/resources/skellett.24/) MundoSK v1.8.5 (https://forums.skunity.com/resources/mundosk.69/) Umbaska v2.0 Beta 5.0541
[12:03:21 ERROR]: #!#! We could not identify which of those are specially related, so this might also be Skript issue.
[12:03:21 ERROR]: #!#! You should try disabling those plugins one by one, trying to find which one causes it.
[12:03:21 ERROR]: #!#! If the error doesn't disappear even after disabling all listed plugins, it is probably Skript issue.
[12:03:21 ERROR]: #!#! In that case, you will be given instruction on how should you report it.
[12:03:21 ERROR]: #!#! On the other hand, if the error disappears when disabling some plugin, report it to author of that plugin.
[12:03:21 ERROR]: #!#! Only if the author tells you to do so, report it to Skript's issue tracker.
[12:03:21 ERROR]: #!#!
[12:03:21 ERROR]: #!#! Stack trace:
[12:03:21 ERROR]: #!#! ch.njol.skript.SkriptAPIException: No class info found for worldborder
[12:03:21 ERROR]: #!#!     at ch.njol.skript.registrations.Classes.getClassInfo(Classes.java:262)
[12:03:21 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.createExprInfo(SkriptParser.java:1837)
[12:03:21 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.getExprInfo(SkriptParser.java:1804)
[12:03:21 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1552)
[12:03:21 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:223)
[12:03:21 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:178)
[12:03:21 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parseSingleExpr(SkriptParser.java:323)
[12:03:21 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parseExpression(SkriptParser.java:640)
[12:03:21 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadItems(ScriptLoader.java:1049)
[12:03:21 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadScript(ScriptLoader.java:678)
[12:03:21 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.lambda$4(ScriptLoader.java:401)
[12:03:21 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:420)
[12:03:21 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.lambda$3(ScriptLoader.java:337)
[12:03:21 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:370)
[12:03:21 ERROR]: #!#!     at ch.njol.skript.Skript.reload(Skript.java:982)
[12:03:21 ERROR]: #!#!     at ch.njol.skript.SkriptCommand.onCommand(SkriptCommand.java:161)
[12:03:21 ERROR]: #!#!     at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[12:03:21 ERROR]: #!#!     at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
[12:03:21 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:641)
[12:03:21 ERROR]: #!#!     at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1162)
[12:03:21 ERROR]: #!#!     at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:997)
[12:03:21 ERROR]: #!#!     at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45)
[12:03:21 ERROR]: #!#!     at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1)
[12:03:21 ERROR]: #!#!     at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13)
[12:03:21 ERROR]: #!#!     at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
[12:03:21 ERROR]: #!#!     at java.util.concurrent.FutureTask.run(Unknown Source)
[12:03:21 ERROR]: #!#!     at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44)
[12:03:21 ERROR]: #!#!     at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:715)
[12:03:21 ERROR]: #!#!     at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374)
[12:03:21 ERROR]: #!#!     at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654)
[12:03:21 ERROR]: #!#!     at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557)
[12:03:21 ERROR]: #!#!     at java.lang.Thread.run(Unknown Source)
[12:03:21 ERROR]: #!#!
[12:03:21 ERROR]: #!#! Version Information:
[12:03:21 ERROR]: #!#!   Skript: 2.5.3 (latest)
[12:03:21 ERROR]: #!#!     Flavor: github-matocolotoe-1.8
[12:03:21 ERROR]: #!#!     Date: 2020-12-22
[12:03:21 ERROR]: #!#!   Bukkit: 1.8.8-R0.1-SNAPSHOT
[12:03:21 ERROR]: #!#!   Minecraft: 1.8.8
[12:03:21 ERROR]: #!#!   Java: 1.8.0_281 (Java HotSpot(TM) 64-Bit Server VM 25.281-b09)
[12:03:21 ERROR]: #!#!   OS: Windows 10 amd64 10.0
[12:03:21 ERROR]: #!#!
[12:03:21 ERROR]: #!#! Server platform: Spigot
[12:03:21 ERROR]: #!#!
[12:03:21 ERROR]: #!#! Current node: loop all players: (tchat.sk, line 6)
[12:03:21 ERROR]: #!#! Current item: null
[12:03:21 ERROR]: #!#!
[12:03:21 ERROR]: #!#! Thread: Server thread
[12:03:21 ERROR]: #!#!
[12:03:21 ERROR]: #!#! Language: english
[12:03:21 ERROR]: #!#! Link parse mode: DISABLED
[12:03:21 ERROR]: #!#!
[12:03:21 ERROR]: #!#! End of Error.
[12:03:21 ERROR]: #!#!

**Comment by Matocolotoe** [comment]
Vous trouverez ici les [documents et tutoriels](https://github.com/Matocolotoe/Skript-1.8/blob/master/README_FR.md) qui vous permettront de correctement mettre à jour votre version.
