### ISSUE TITLE
Problem with ItemStack

### ISSUE THREAD

**Issue by wallace4BR** [Matocolotoe/Skript-1.8#36]
### Description
Getting an itemstack from player's hand is throwing error as there's no `getItemInMainHand()'` in 1.8

### Steps to Reproduce
```code
on right click:
    broadcast "%player's tool%"
```

### Expected Behavior
It should return the itemstack

### Errors / Screenshots
```code
00:29:18 ERROR]: Could not pass event PlayerInteractEvent to Skript v2.6-beta2
java.lang.NoSuchMethodError: 'org.bukkit.inventory.ItemStack org.bukkit.inventor
y.EntityEquipment.getItemInMainHand()'
        at ch.njol.skript.util.slot.EquipmentSlot$EquipSlot$1.get(EquipmentSlot.
java:43) ~[?:?]
        at ch.njol.skript.util.slot.EquipmentSlot.getItem(EquipmentSlot.java:158
) ~[?:?]
        at ch.njol.skript.classes.data.SkriptClasses$16.toString(SkriptClasses.j
ava:669) ~[?:?]
        at ch.njol.skript.classes.data.SkriptClasses$16.toString(SkriptClasses.j
ava:661) ~[?:?]
        at ch.njol.skript.registrations.Classes.toString(Classes.java:625) ~[?:?
]
        at ch.njol.skript.registrations.Classes.toString(Classes.java:654) ~[?:?
]
        at ch.njol.skript.registrations.Classes.toString(Classes.java:647) ~[?:?
]
        at ch.njol.skript.lang.VariableString.toString(VariableString.java:449)
~[?:?]
        at ch.njol.skript.lang.VariableString.getArray(VariableString.java:666)
~[?:?]
        at ch.njol.skript.lang.VariableString.getArray(VariableString.java:64) ~
[?:?]
        at ch.njol.skript.effects.EffBroadcast.execute(EffBroadcast.java:70) ~[?
:?]
        at ch.njol.skript.lang.Effect.run(Effect.java:51) ~[?:?]
        at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:60) ~[?:?]
        at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:88) ~[?:?]
        at ch.njol.skript.lang.Trigger.execute(Trigger.java:56) ~[?:?]
        at ch.njol.skript.SkriptEventHandler.check(SkriptEventHandler.java:142)
~[?:?]
        at ch.njol.skript.SkriptEventHandler.access$000(SkriptEventHandler.java:
53) ~[?:?]
        at ch.njol.skript.SkriptEventHandler$PriorityListener.lambda$new$0(Skrip
tEventHandler.java:71) ~[?:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:7
8) ~[patched.jar:git-PaperSpigot-"4c7641d"]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.jav
a:62) ~[patched.jar:git-PaperSpigot-"4c7641d"]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.j
ava:517) [patched.jar:git-PaperSpigot-"4c7641d"]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.j
ava:502) [patched.jar:git-PaperSpigot-"4c7641d"]
        at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.callPlayerInte
ractEvent(CraftEventFactory.java:228) [patched.jar:git-PaperSpigot-"4c7641d"]
        at net.minecraft.server.v1_8_R3.PlayerInteractManager.interact(PlayerInt
eractManager.java:463) [patched.jar:git-PaperSpigot-"4c7641d"]
        at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java
:763) [patched.jar:git-PaperSpigot-"4c7641d"]
        at net.minecraft.server.v1_8_R3.PacketPlayInBlockPlace.a(PacketPlayInBlo
ckPlace.java:52) [patched.jar:git-PaperSpigot-"4c7641d"]
        at net.minecraft.server.v1_8_R3.PacketPlayInBlockPlace.a(PacketPlayInBlo
ckPlace.java:1) [patched.jar:git-PaperSpigot-"4c7641d"]
        at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:1
3) [patched.jar:git-PaperSpigot-"4c7641d"]
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executo
rs.java:515) [?:?]
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) [?
:?]
        at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [patched.ja
r:git-PaperSpigot-"4c7641d"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:7
74) [patched.jar:git-PaperSpigot-"4c7641d"]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:3
78) [patched.jar:git-PaperSpigot-"4c7641d"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:7
13) [patched.jar:git-PaperSpigot-"4c7641d"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java
:616) [patched.jar:git-PaperSpigot-"4c7641d"]
        at java.base/java.lang.Thread.run(Thread.java:831) [?:?]
```

Server version/platform: paper 1.8.8
Skript-1.8 version: 2.6 beta 2

**Comment by wallace4BR** [comment]
nvm, it has been fixed on the latest build

**Comment by Matocolotoe** [comment]
I'll leave that open since this hasn't been fixed in an actual release yet.
