### ISSUE TITLE
Error when loading plugin

### ISSUE THREAD

**Issue by ghost** [Matocolotoe/Skript-1.8#48]
### Skript Version

```
[08:41:37 INFO]: [Skript] Disabling Skript v2.2-dev36
[08:41:38 WARN]: org.bukkit.plugin.InvalidPluginException: java.lang.IllegalStateException: Cannot create multiple instances of Skript!
[08:41:38 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:135)
[08:41:38 WARN]:        at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:329)
[08:41:38 WARN]:        at com.rylinaux.plugman.util.PluginUtil.load(PluginUtil.java:299)
[08:41:38 WARN]:        at com.rylinaux.plugman.util.PluginUtil.load(PluginUtil.java:267)
[08:41:38 WARN]:        at com.rylinaux.plugman.util.PluginUtil.reload(PluginUtil.java:393)
[08:41:38 WARN]:        at com.rylinaux.plugman.command.ReloadCommand.execute(ReloadCommand.java:122)
[08:41:38 WARN]:        at com.rylinaux.plugman.PlugManCommandHandler.onCommand(PlugManCommandHandler.java:95)
[08:41:38 WARN]:        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[08:41:38 WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
[08:41:38 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:641)
[08:41:38 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchServerCommand(CraftServer.java:627)
[08:41:38 WARN]:        at net.minecraft.server.v1_8_R3.DedicatedServer.aO(DedicatedServer.java:412)
[08:41:38 WARN]:        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:375)
[08:41:38 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654)
[08:41:38 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557)
[08:41:38 WARN]:        at java.lang.Thread.run(Thread.java:748)
[08:41:38 WARN]: Caused by: java.lang.IllegalStateException: Cannot create multiple instances of Skript!
[08:41:38 WARN]:        at ch.njol.skript.Skript.<init>(Skript.java:178)
[08:41:38 WARN]:        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[08:41:38 WARN]:        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[08:41:38 WARN]:        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[08:41:38 WARN]:        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
[08:41:38 WARN]:        at java.lang.Class.newInstance(Class.java:442)
[08:41:38 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:76)
[08:41:38 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:131)
[08:41:38 WARN]:        ... 15 more
```

### Bug Description

[08:41:37 INFO]: [Skript] Disabling Skript v2.2-dev36
[08:41:38 WARN]: org.bukkit.plugin.InvalidPluginException: java.lang.IllegalStateException: Cannot create multiple instances of Skript!
[08:41:38 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:135)
[08:41:38 WARN]:        at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:329)
[08:41:38 WARN]:        at com.rylinaux.plugman.util.PluginUtil.load(PluginUtil.java:299)
[08:41:38 WARN]:        at com.rylinaux.plugman.util.PluginUtil.load(PluginUtil.java:267)
[08:41:38 WARN]:        at com.rylinaux.plugman.util.PluginUtil.reload(PluginUtil.java:393)
[08:41:38 WARN]:        at com.rylinaux.plugman.command.ReloadCommand.execute(ReloadCommand.java:122)
[08:41:38 WARN]:        at com.rylinaux.plugman.PlugManCommandHandler.onCommand(PlugManCommandHandler.java:95)
[08:41:38 WARN]:        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[08:41:38 WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
[08:41:38 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:641)
[08:41:38 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchServerCommand(CraftServer.java:627)
[08:41:38 WARN]:        at net.minecraft.server.v1_8_R3.DedicatedServer.aO(DedicatedServer.java:412)
[08:41:38 WARN]:        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:375)
[08:41:38 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654)
[08:41:38 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557)
[08:41:38 WARN]:        at java.lang.Thread.run(Thread.java:748)
[08:41:38 WARN]: Caused by: java.lang.IllegalStateException: Cannot create multiple instances of Skript!
[08:41:38 WARN]:        at ch.njol.skript.Skript.<init>(Skript.java:178)
[08:41:38 WARN]:        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[08:41:38 WARN]:        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[08:41:38 WARN]:        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[08:41:38 WARN]:        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
[08:41:38 WARN]:        at java.lang.Class.newInstance(Class.java:442)
[08:41:38 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:76)
[08:41:38 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:131)
[08:41:38 WARN]:        ... 15 more

### Expected Behavior

[08:41:37 INFO]: [Skript] Disabling Skript v2.2-dev36
[08:41:38 WARN]: org.bukkit.plugin.InvalidPluginException: java.lang.IllegalStateException: Cannot create multiple instances of Skript!
[08:41:38 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:135)
[08:41:38 WARN]:        at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:329)
[08:41:38 WARN]:        at com.rylinaux.plugman.util.PluginUtil.load(PluginUtil.java:299)
[08:41:38 WARN]:        at com.rylinaux.plugman.util.PluginUtil.load(PluginUtil.java:267)
[08:41:38 WARN]:        at com.rylinaux.plugman.util.PluginUtil.reload(PluginUtil.java:393)
[08:41:38 WARN]:        at com.rylinaux.plugman.command.ReloadCommand.execute(ReloadCommand.java:122)
[08:41:38 WARN]:        at com.rylinaux.plugman.PlugManCommandHandler.onCommand(PlugManCommandHandler.java:95)
[08:41:38 WARN]:        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[08:41:38 WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
[08:41:38 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:641)
[08:41:38 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchServerCommand(CraftServer.java:627)
[08:41:38 WARN]:        at net.minecraft.server.v1_8_R3.DedicatedServer.aO(DedicatedServer.java:412)
[08:41:38 WARN]:        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:375)
[08:41:38 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654)
[08:41:38 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557)
[08:41:38 WARN]:        at java.lang.Thread.run(Thread.java:748)
[08:41:38 WARN]: Caused by: java.lang.IllegalStateException: Cannot create multiple instances of Skript!
[08:41:38 WARN]:        at ch.njol.skript.Skript.<init>(Skript.java:178)
[08:41:38 WARN]:        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[08:41:38 WARN]:        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[08:41:38 WARN]:        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[08:41:38 WARN]:        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
[08:41:38 WARN]:        at java.lang.Class.newInstance(Class.java:442)
[08:41:38 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:76)
[08:41:38 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:131)
[08:41:38 WARN]:        ... 15 more

### Steps to Reproduce

[08:41:37 INFO]: [Skript] Disabling Skript v2.2-dev36
[08:41:38 WARN]: org.bukkit.plugin.InvalidPluginException: java.lang.IllegalStateException: Cannot create multiple instances of Skript!
[08:41:38 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:135)
[08:41:38 WARN]:        at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:329)
[08:41:38 WARN]:        at com.rylinaux.plugman.util.PluginUtil.load(PluginUtil.java:299)
[08:41:38 WARN]:        at com.rylinaux.plugman.util.PluginUtil.load(PluginUtil.java:267)
[08:41:38 WARN]:        at com.rylinaux.plugman.util.PluginUtil.reload(PluginUtil.java:393)
[08:41:38 WARN]:        at com.rylinaux.plugman.command.ReloadCommand.execute(ReloadCommand.java:122)
[08:41:38 WARN]:        at com.rylinaux.plugman.PlugManCommandHandler.onCommand(PlugManCommandHandler.java:95)
[08:41:38 WARN]:        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[08:41:38 WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
[08:41:38 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:641)
[08:41:38 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchServerCommand(CraftServer.java:627)
[08:41:38 WARN]:        at net.minecraft.server.v1_8_R3.DedicatedServer.aO(DedicatedServer.java:412)
[08:41:38 WARN]:        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:375)
[08:41:38 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654)
[08:41:38 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557)
[08:41:38 WARN]:        at java.lang.Thread.run(Thread.java:748)
[08:41:38 WARN]: Caused by: java.lang.IllegalStateException: Cannot create multiple instances of Skript!
[08:41:38 WARN]:        at ch.njol.skript.Skript.<init>(Skript.java:178)
[08:41:38 WARN]:        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[08:41:38 WARN]:        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[08:41:38 WARN]:        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[08:41:38 WARN]:        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
[08:41:38 WARN]:        at java.lang.Class.newInstance(Class.java:442)
[08:41:38 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:76)
[08:41:38 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:131)
[08:41:38 WARN]:        ... 15 more

### Errors or Screenshots

```
[08:41:37 INFO]: [Skript] Disabling Skript v2.2-dev36
[08:41:38 WARN]: org.bukkit.plugin.InvalidPluginException: java.lang.IllegalStateException: Cannot create multiple instances of Skript!
[08:41:38 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:135)
[08:41:38 WARN]:        at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:329)
[08:41:38 WARN]:        at com.rylinaux.plugman.util.PluginUtil.load(PluginUtil.java:299)
[08:41:38 WARN]:        at com.rylinaux.plugman.util.PluginUtil.load(PluginUtil.java:267)
[08:41:38 WARN]:        at com.rylinaux.plugman.util.PluginUtil.reload(PluginUtil.java:393)
[08:41:38 WARN]:        at com.rylinaux.plugman.command.ReloadCommand.execute(ReloadCommand.java:122)
[08:41:38 WARN]:        at com.rylinaux.plugman.PlugManCommandHandler.onCommand(PlugManCommandHandler.java:95)
[08:41:38 WARN]:        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[08:41:38 WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
[08:41:38 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:641)
[08:41:38 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchServerCommand(CraftServer.java:627)
[08:41:38 WARN]:        at net.minecraft.server.v1_8_R3.DedicatedServer.aO(DedicatedServer.java:412)
[08:41:38 WARN]:        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:375)
[08:41:38 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654)
[08:41:38 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557)
[08:41:38 WARN]:        at java.lang.Thread.run(Thread.java:748)
[08:41:38 WARN]: Caused by: java.lang.IllegalStateException: Cannot create multiple instances of Skript!
[08:41:38 WARN]:        at ch.njol.skript.Skript.<init>(Skript.java:178)
[08:41:38 WARN]:        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[08:41:38 WARN]:        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[08:41:38 WARN]:        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[08:41:38 WARN]:        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
[08:41:38 WARN]:        at java.lang.Class.newInstance(Class.java:442)
[08:41:38 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:76)
[08:41:38 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:131)
[08:41:38 WARN]:        ... 15 more
```

### Other

[08:41:37 INFO]: [Skript] Disabling Skript v2.2-dev36
[08:41:38 WARN]: org.bukkit.plugin.InvalidPluginException: java.lang.IllegalStateException: Cannot create multiple instances of Skript!
[08:41:38 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:135)
[08:41:38 WARN]:        at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:329)
[08:41:38 WARN]:        at com.rylinaux.plugman.util.PluginUtil.load(PluginUtil.java:299)
[08:41:38 WARN]:        at com.rylinaux.plugman.util.PluginUtil.load(PluginUtil.java:267)
[08:41:38 WARN]:        at com.rylinaux.plugman.util.PluginUtil.reload(PluginUtil.java:393)
[08:41:38 WARN]:        at com.rylinaux.plugman.command.ReloadCommand.execute(ReloadCommand.java:122)
[08:41:38 WARN]:        at com.rylinaux.plugman.PlugManCommandHandler.onCommand(PlugManCommandHandler.java:95)
[08:41:38 WARN]:        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[08:41:38 WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
[08:41:38 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:641)
[08:41:38 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchServerCommand(CraftServer.java:627)
[08:41:38 WARN]:        at net.minecraft.server.v1_8_R3.DedicatedServer.aO(DedicatedServer.java:412)
[08:41:38 WARN]:        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:375)
[08:41:38 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654)
[08:41:38 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557)
[08:41:38 WARN]:        at java.lang.Thread.run(Thread.java:748)
[08:41:38 WARN]: Caused by: java.lang.IllegalStateException: Cannot create multiple instances of Skript!
[08:41:38 WARN]:        at ch.njol.skript.Skript.<init>(Skript.java:178)
[08:41:38 WARN]:        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[08:41:38 WARN]:        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[08:41:38 WARN]:        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[08:41:38 WARN]:        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
[08:41:38 WARN]:        at java.lang.Class.newInstance(Class.java:442)
[08:41:38 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:76)
[08:41:38 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:131)
[08:41:38 WARN]:        ... 15 more

### Agreement

- [X] I have read the guidelines above and confirm I am following them with this report.

**Comment by ghost** [comment]
[08:41:37 INFO]: [Skript] Disabling Skript v2.2-dev36
[08:41:38 WARN]: org.bukkit.plugin.InvalidPluginException: java.lang.IllegalStateException: Cannot create multiple instances of Skript!
[08:41:38 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:135)
[08:41:38 WARN]:        at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:329)
[08:41:38 WARN]:        at com.rylinaux.plugman.util.PluginUtil.load(PluginUtil.java:299)
[08:41:38 WARN]:        at com.rylinaux.plugman.util.PluginUtil.load(PluginUtil.java:267)
[08:41:38 WARN]:        at com.rylinaux.plugman.util.PluginUtil.reload(PluginUtil.java:393)
[08:41:38 WARN]:        at com.rylinaux.plugman.command.ReloadCommand.execute(ReloadCommand.java:122)
[08:41:38 WARN]:        at com.rylinaux.plugman.PlugManCommandHandler.onCommand(PlugManCommandHandler.java:95)
[08:41:38 WARN]:        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[08:41:38 WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
[08:41:38 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:641)
[08:41:38 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchServerCommand(CraftServer.java:627)
[08:41:38 WARN]:        at net.minecraft.server.v1_8_R3.DedicatedServer.aO(DedicatedServer.java:412)
[08:41:38 WARN]:        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:375)
[08:41:38 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654)
[08:41:38 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557)
[08:41:38 WARN]:        at java.lang.Thread.run(Thread.java:748)
[08:41:38 WARN]: Caused by: java.lang.IllegalStateException: Cannot create multiple instances of Skript!
[08:41:38 WARN]:        at ch.njol.skript.Skript.<init>(Skript.java:178)
[08:41:38 WARN]:        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[08:41:38 WARN]:        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[08:41:38 WARN]:        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[08:41:38 WARN]:        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
[08:41:38 WARN]:        at java.lang.Class.newInstance(Class.java:442)
[08:41:38 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:76)
[08:41:38 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:131)
[08:41:38 WARN]:        ... 15 more

**Comment by Matocolotoe** [comment]
`Skript v2.2-dev36`

This is not the right place for trolling.
