### ISSUE TITLE
On drop with a damaged sword

### ISSUE THREAD

**Issue by Souipi** [Matocolotoe/Skript-1.8#69]
### Skript Version

```
> [Skript] Skript's aliases can be found here: https://github.com/SkriptLang/skript-aliases
> [Skript] Skript's documentation can be found here: https://skriptlang.github.io/Skript
> [Skript] Skript's tutorials can be found here: https://docs.skriptlang.org/tutorials
> [Skript] Server Version: git-PaperSpigot-445 (MC: 1.8.8)
> [Skript] Skript Version: 2.6.4-for-1.8
> [Skript] Installed Skript Addons:
> [Skript]  - skript-placeholders v1.5.2 (https://github.com/APickledWalrus/skript-placeholders)
> [Skript]  - skript-gui v1.3 (https://github.com/APickledWalrus/skript-gui)
> [Skript]  - BungeeSK v2.0.0 (https://github.com/ZorgBtw/BungeeSK)
> [Skript]  - skript-yaml v1.4.1
> [Skript]  - skript-reflect v2.3 (https://github.com/TPGamesNL/skript-reflect)
> [Skript]  - skRayFall v1.9.25 (https://sk.rayfall.net/)
> [Skript]  - SkQuery v4.1.6
> [Skript]  - SkBee v1.10.2 (https://github.com/ShaneBeee/SkBee)
> [Skript] Installed dependencies:
> [Skript]  - WorldGuard v6.1.3-SNAPSHOT;c904242
```

### Bug Description

Si vous avez une épée qui est utilisé ( la durabilité ) l'event on drop: ne ce déclanche pas

### Expected Behavior

Que l'event fonctionne

### Steps to Reproduce

Taper une entité avec une épée.

Et mettre un event on drop: sur un skript avec un debug

### Errors or Screenshots

```
Could not pass event PlayerDropItemEvent to Skript v2.6.4-for-1.8
java.lang.AssertionError: null
        at ch.njol.skript.aliases.AliasesMap.matchAlias(AliasesMap.java:198) ~[?:?]
        at ch.njol.skript.aliases.AliasesProvider.getAliasData(AliasesProvider.java:354) ~[?:?]
        at ch.njol.skript.aliases.AliasesProvider.getMaterialName(AliasesProvider.java:372) ~[?:?]
        at ch.njol.skript.aliases.Aliases.getMaterialNameData(Aliases.java:187) ~[?:?]
        at ch.njol.skript.aliases.Aliases.getGender(Aliases.java:202) ~[?:?]
        at ch.njol.skript.aliases.ItemData.getGender(ItemData.java:266) ~[?:?]
        at ch.njol.skript.aliases.ItemType.toString(ItemType.java:1027) ~[?:?]
        at ch.njol.skript.aliases.ItemType.toString(ItemType.java:1004) ~[?:?]
        at ch.njol.skript.classes.data.SkriptClasses$4.toString(SkriptClasses.java:209) ~[?:?]
        at ch.njol.skript.classes.data.SkriptClasses$4.toString(SkriptClasses.java:200) ~[?:?]
        at ch.njol.skript.registrations.Classes.toString(Classes.java:619) ~[?:?]
        at ch.njol.skript.registrations.Classes.toString(Classes.java:648) ~[?:?]
        at ch.njol.skript.registrations.Classes.toString(Classes.java:641) ~[?:?]
        at ch.njol.skript.lang.VariableString.toString(VariableString.java:373) ~[?:?]
        at ch.njol.skript.lang.VariableString.getAll(VariableString.java:596) ~[?:?]
        at ch.njol.skript.effects.EffBroadcast.execute(EffBroadcast.java:93) ~[?:?]
        at ch.njol.skript.lang.Effect.run(Effect.java:50) ~[?:?]
        at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:61) ~[?:?]
        at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:89) ~[?:?]
        at ch.njol.skript.lang.Trigger.execute(Trigger.java:56) ~[?:?]
        at ch.njol.skript.SkriptEventHandler.check(SkriptEventHandler.java:142) ~[?:?]
        at ch.njol.skript.SkriptEventHandler.access$000(SkriptEventHandler.java:53) ~[?:?]
        at ch.njol.skript.SkriptEventHandler$PriorityListener.lambda$new$0(SkriptEventHandler.java:71) ~[?:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[patched_1.8.8.jar:git-PaperSpigot-445]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.8.8.jar:git-PaperSpigot-445]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:517) [patched_1.8.8.jar:git-PaperSpigot-445]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:502) [patched_1.8.8.jar:git-PaperSpigot-445]
        at net.minecraft.server.v1_8_R3.EntityHuman.a(EntityHuman.java:602) [patched_1.8.8.jar:git-PaperSpigot-445]
        at net.minecraft.server.v1_8_R3.EntityHuman.a(EntityHuman.java:555) [patched_1.8.8.jar:git-PaperSpigot-445]
        at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:595) [patched_1.8.8.jar:git-PaperSpigot-445]
        at net.minecraft.server.v1_8_R3.PacketPlayInBlockDig.a(SourceFile:40) [patched_1.8.8.jar:git-PaperSpigot-445]
        at net.minecraft.server.v1_8_R3.PacketPlayInBlockDig.a(SourceFile:10) [patched_1.8.8.jar:git-PaperSpigot-445]
        at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [patched_1.8.8.jar:git-PaperSpigot-445]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_351]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_351]
        at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [patched_1.8.8.jar:git-PaperSpigot-445]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:774) [patched_1.8.8.jar:git-PaperSpigot-445]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378) [patched_1.8.8.jar:git-PaperSpigot-445]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:713) [patched_1.8.8.jar:git-PaperSpigot-445]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616) [patched_1.8.8.jar:git-PaperSpigot-445]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_351]
```

### Other

Na x)

### Agreement

- [x] I have read the guidelines above and confirm I am following them with this report.

**Comment by Matocolotoe** [comment]
Duplicate of #60
