### ISSUE TITLE
Bug with wooden hoes, or all hoes in general.

### ISSUE THREAD

**Issue by Sulphinx** [Matocolotoe/Skript-1.8#72]
### Skript Version

[09:50:47] [Server thread/INFO]: [Skript] Skript's aliases can be found here: https://github.com/SkriptLang/skript-aliases
[09:50:47] [Server thread/INFO]: [Skript] Skript's documentation can be found here: https://docs.skriptlang.org/
[09:50:47] [Server thread/INFO]: [Skript] Skript's tutorials can be found here: https://docs.skriptlang.org/tutorials
[09:50:47] [Server thread/INFO]: [Skript] Server Version: git-PaperSpigot-445 (MC: 1.8.8)
[09:50:47] [Server thread/INFO]: [Skript] Skript Version: 2.6.4-for-1.8
[09:50:47] [Server thread/INFO]: [Skript] Installed Skript Addons: 
[09:50:47] [Server thread/INFO]: [Skript]  - skript-placeholders v1.5.2 (https://github.com/APickledWalrus/skript-placeholders)
[09:50:47] [Server thread/INFO]: [Skript]  - Skellett v1.9.8 (https://forums.skunity.com/resources/skellett.24/)
[09:50:47] [Server thread/INFO]: [Skript]  - skript-yaml v1.4
[09:50:47] [Server thread/INFO]: [Skript]  - SkEssentials v0.0.1
[09:50:47] [Server thread/INFO]: [Skript]  - skript-reflect v2.3 (https://github.com/TPGamesNL/skript-reflect)
[09:50:47] [Server thread/INFO]: [Skript]  - skRayFall v1.9.25 (https://sk.rayfall.net/)
[09:50:47] [Server thread/INFO]: [Skript]  - SkQuery v4.1.6
[09:50:47] [Server thread/INFO]: [Skript]  - SkBee v1.10.2 (https://github.com/ShaneBeee/SkBee)
[09:50:47] [Server thread/INFO]: [Skript]  - LabyModSK v1.1.0
[09:50:47] [Server thread/INFO]: [Skript] Installed dependencies: 
[09:50:47] [Server thread/INFO]: [Skript]  - Vault v1.7.3-b131
[09:50:47] [Server thread/INFO]: [Skript]  - WorldGuard v6.1.3-SNAPSHOT;c904242

### Bug Description

It was supposed to send player's tool which is a wooden hoe, but instead threw an error in console.

### Expected Behavior

Sending player's held item, but it did nothing and threw an error instead.

### Steps to Reproduce

on rightclick on dirt or grass block:
	send "%player's held item%" # or player's tool

### Errors or Screenshots

[09:47:34] [Server thread/ERROR]: Could not pass event PlayerInteractEvent to Skript v2.6.4-for-1.8
java.lang.AssertionError: null
	at ch.njol.skript.aliases.AliasesMap.matchAlias(AliasesMap.java:198) ~[?:?]
	at ch.njol.skript.aliases.AliasesProvider.getAliasData(AliasesProvider.java:354) ~[?:?]
	at ch.njol.skript.aliases.AliasesProvider.getMaterialName(AliasesProvider.java:372) ~[?:?]
	at ch.njol.skript.aliases.Aliases.getMaterialNameData(Aliases.java:187) ~[?:?]
	at ch.njol.skript.aliases.Aliases.getGender(Aliases.java:202) ~[?:?]
	at ch.njol.skript.aliases.ItemData.getGender(ItemData.java:266) ~[?:?]
	at ch.njol.skript.aliases.ItemType.toString(ItemType.java:1027) ~[?:?]
	at ch.njol.skript.aliases.ItemType.toString(ItemType.java:1004) ~[?:?]
	at ch.njol.skript.aliases.ItemType.toString(ItemType.java:1077) ~[?:?]
	at ch.njol.skript.classes.data.SkriptClasses$16.toString(SkriptClasses.java:642) ~[?:?]
	at ch.njol.skript.classes.data.SkriptClasses$16.toString(SkriptClasses.java:631) ~[?:?]
	at ch.njol.skript.registrations.Classes.toString(Classes.java:619) ~[?:?]
	at ch.njol.skript.registrations.Classes.toString(Classes.java:648) ~[?:?]
	at ch.njol.skript.registrations.Classes.toString(Classes.java:641) ~[?:?]
	at ch.njol.skript.lang.VariableString.getMessageComponents(VariableString.java:442) ~[?:?]
	at ch.njol.skript.effects.EffMessage.sendMessage(EffMessage.java:120) ~[?:?]
	at ch.njol.skript.effects.EffMessage.execute(EffMessage.java:108) ~[?:?]
	at ch.njol.skript.lang.Effect.run(Effect.java:50) ~[?:?]
	at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:61) ~[?:?]
	at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:89) ~[?:?]
	at ch.njol.skript.lang.Trigger.execute(Trigger.java:56) ~[?:?]
	at ch.njol.skript.SkriptEventHandler.check(SkriptEventHandler.java:142) ~[?:?]
	at ch.njol.skript.SkriptEventHandler.access$000(SkriptEventHandler.java:53) ~[?:?]
	at ch.njol.skript.SkriptEventHandler$PriorityListener.lambda$new$0(SkriptEventHandler.java:71) ~[?:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[patched_1.8.8.jar:git-PaperSpigot-445]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.8.8.jar:git-PaperSpigot-445]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:517) [patched_1.8.8.jar:git-PaperSpigot-445]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:502) [patched_1.8.8.jar:git-PaperSpigot-445]
	at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:228) [patched_1.8.8.jar:git-PaperSpigot-445]
	at net.minecraft.server.v1_8_R3.PlayerInteractManager.interact(PlayerInteractManager.java:463) [patched_1.8.8.jar:git-PaperSpigot-445]
	at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:763) [patched_1.8.8.jar:git-PaperSpigot-445]
	at net.minecraft.server.v1_8_R3.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:52) [patched_1.8.8.jar:git-PaperSpigot-445]
	at net.minecraft.server.v1_8_R3.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:1) [patched_1.8.8.jar:git-PaperSpigot-445]
	at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [patched_1.8.8.jar:git-PaperSpigot-445]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_252]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_252]
	at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [patched_1.8.8.jar:git-PaperSpigot-445]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:774) [patched_1.8.8.jar:git-PaperSpigot-445]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378) [patched_1.8.8.jar:git-PaperSpigot-445]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:713) [patched_1.8.8.jar:git-PaperSpigot-445]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616) [patched_1.8.8.jar:git-PaperSpigot-445]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_252]

### Agreement

- [X] I have read the guidelines above and confirm I am following them with this report.

**Comment by Matocolotoe** [comment]
Use the latest build from https://github.com/Matocolotoe/Skript-1.8/actions/runs/4801247898
