### ISSUE TITLE
Cannnot start the server

### ISSUE THREAD

**Issue by valeryadf** [Matocolotoe/Skript-1.8#73]
### Skript Version

```
2.6.4
```

### Bug Description

server doesn't start?

### Expected Behavior

eheh

### Steps to Reproduce

Start the servr

### Errors or Screenshots

```
 Error occurred while enabling Skript v2.6.4-for-1.8 (Is it up to date?)
java.lang.NoSuchMethodError: 'boolean ch.njol.skript.localization.Language.keyExistsDefault(java.lang.String)'
        at ch.njol.skript.localization.Noun.lambda$static$0(Noun.java:321) ~[?:?]
        at ch.njol.skript.localization.Language.addListener(Language.java:333) ~[?:?]
        at ch.njol.skript.localization.Noun.<clinit>(Noun.java:315) ~[?:?]
        at ch.njol.skript.classes.ClassInfo.<init>(ClassInfo.java:102) ~[?:?]
        at ch.njol.skript.classes.data.JavaClasses.<clinit>(JavaClasses.java:46) ~[?:?]
        at ch.njol.skript.Skript.onEnable(Skript.java:431) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[server.jar:git-Spigot-21fe707-e1ebe52]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340) [server.jar:git-Spigot-21fe707-e1ebe52]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [server.jar:git-Spigot-21fe707-e1ebe52]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:357) [server.jar:git-Spigot-21fe707-e1ebe52]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:317) [server.jar:git-Spigot-21fe707-e1ebe52]
        at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:414) [server.jar:git-Spigot-21fe707-e1ebe52]
        at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:378) [server.jar:git-Spigot-21fe707-e1ebe52]
        at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:333) [server.jar:git-Spigot-21fe707-e1ebe52]
        at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:263) [server.jar:git-Spigot-21fe707-e1ebe52]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:525) [server.jar:git-Spigot-21fe707-e1ebe52]
        at java.base/java.lang.Thread.run(Thread.java:829) [?:?]
```

### Other

no

### Agreement

- [X] I have read the guidelines above and confirm I am following them with this report.

**Comment by Matocolotoe** [comment]
This is likely caused by an addon. What addons have you got ?

**Comment by Matocolotoe** [comment]
Closing due to lack of response.
