### ISSUE TITLE
Error occurred while enabling Skript v2.6.4-for-1.8 (Is it up to date?)

### ISSUE THREAD

**Issue by TarikCoding** [Matocolotoe/Skript-1.8#74]
### Skript Version

I cant make /skript info because the script dont load.

Skript: Skript-1.8
Minecraft Version: 1.8
Spigot

### Bug Description

When i start server and then comes in the Console Logs this error:

Error occurred while enabling Skript v2.6.4-for-1.8 (Is it up to date?)
java.lang.NoClassDefFoundError: com/google/gson/GsonBuilder
        at ch.njol.skript.update.ReleaseManifest.load(ReleaseManifest.java:48) ~[?:?]
        at ch.njol.skript.SkriptUpdater.loadManifest(SkriptUpdater.java:76) ~[?:?]
        at ch.njol.skript.SkriptUpdater.<init>(SkriptUpdater.java:59) ~[?:?]
        at ch.njol.skript.Skript.onEnable(Skript.java:354) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[spigot.jar:git-Spigot-c3c767f-33d5de3]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:335) [spigot.jar:git-Spigot-c3c767f-33d5de3]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot.jar:git-Spigot-c3c767f-33d5de3]
        at org.bukkit.craftbukkit.v1_8_R1.CraftServer.loadPlugin(CraftServer.java:356) [spigot.jar:git-Spigot-c3c767f-33d5de3]
        at org.bukkit.craftbukkit.v1_8_R1.CraftServer.enablePlugins(CraftServer.java:316) [spigot.jar:git-Spigot-c3c767f-33d5de3]
        at net.minecraft.server.v1_8_R1.MinecraftServer.q(MinecraftServer.java:402) [spigot.jar:git-Spigot-c3c767f-33d5de3]
        at net.minecraft.server.v1_8_R1.MinecraftServer.k(MinecraftServer.java:370) [spigot.jar:git-Spigot-c3c767f-33d5de3]
        at net.minecraft.server.v1_8_R1.MinecraftServer.a(MinecraftServer.java:325) [spigot.jar:git-Spigot-c3c767f-33d5de3]
        at net.minecraft.server.v1_8_R1.DedicatedServer.init(DedicatedServer.java:211) [spigot.jar:git-Spigot-c3c767f-33d5de3]
        at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:505) [spigot.jar:git-Spigot-c3c767f-33d5de3]
        at java.base/java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.ClassNotFoundException: com.google.gson.GsonBuilder
        at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:445) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101) ~[spigot.jar:git-Spigot-c3c767f-33d5de3]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[spigot.jar:git-Spigot-c3c767f-33d5de3]
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:592) ~[?:?]
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?]

![image](https://github.com/Matocolotoe/Skript-1.8/assets/114253224/e784498d-5742-4f52-a730-d578c28e8d6f)

### Expected Behavior

Too start the script normally

### Steps to Reproduce

I only start the server

### Errors or Screenshots

![image](https://github.com/Matocolotoe/Skript-1.8/assets/114253224/8a435cb0-69ce-48e4-a44d-95d68d07df59)

### Other

--

### Agreement

- [X] I have read the guidelines above and confirm I am following them with this report.

**Comment by Matocolotoe** [comment]
> ### Skript Version
> 
> I cant make /skript info because the script dont load.
> 
> Skript: Skript-1.8 Minecraft Version: 1.8 Spigot
> ### Bug Description
> 
> When i start server and then comes in the Console Logs this error:
> 
> Error occurred while enabling Skript v2.6.4-for-1.8 (Is it up to date?) java.lang.NoClassDefFoundError: com/google/gson/GsonBuilder at ch.njol.skript.update.ReleaseManifest.load(ReleaseManifest.java:48) ~[?:?] at ch.njol.skript.SkriptUpdater.loadManifest(SkriptUpdater.java:76) ~[?:?] at ch.njol.skript.SkriptUpdater.(SkriptUpdater.java:59) ~[?:?] at ch.njol.skript.Skript.onEnable(Skript.java:354) ~[?:?] at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[spigot.jar:git-Spigot-c3c767f-33d5de3] at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:335) [spigot.jar:git-Spigot-c3c767f-33d5de3] at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot.jar:git-Spigot-c3c767f-33d5de3] at org.bukkit.craftbukkit.v1_8_R1.CraftServer.loadPlugin(CraftServer.java:356) [spigot.jar:git-Spigot-c3c767f-33d5de3] at org.bukkit.craftbukkit.v1_8_R1.CraftServer.enablePlugins(CraftServer.java:316) [spigot.jar:git-Spigot-c3c767f-33d5de3] at net.minecraft.server.v1_8_R1.MinecraftServer.q(MinecraftServer.java:402) [spigot.jar:git-Spigot-c3c767f-33d5de3] at net.minecraft.server.v1_8_R1.MinecraftServer.k(MinecraftServer.java:370) [spigot.jar:git-Spigot-c3c767f-33d5de3] at net.minecraft.server.v1_8_R1.MinecraftServer.a(MinecraftServer.java:325) [spigot.jar:git-Spigot-c3c767f-33d5de3] at net.minecraft.server.v1_8_R1.DedicatedServer.init(DedicatedServer.java:211) [spigot.jar:git-Spigot-c3c767f-33d5de3] at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:505) [spigot.jar:git-Spigot-c3c767f-33d5de3] at java.base/java.lang.Thread.run(Thread.java:833) [?:?] Caused by: java.lang.ClassNotFoundException: com.google.gson.GsonBuilder at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:445) ~[?:?] at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101) ~[spigot.jar:git-Spigot-c3c767f-33d5de3] at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[spigot.jar:git-Spigot-c3c767f-33d5de3] at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:592) ~[?:?] at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?]
> 
> ![image](https://user-images.githubusercontent.com/114253224/275988402-e784498d-5742-4f52-a730-d578c28e8d6f.png)
> ### Expected Behavior
> 
> Too start the script normally
> ### Steps to Reproduce
> 
> I only start the server
> ### Errors or Screenshots
> 
> ![image](https://user-images.githubusercontent.com/114253224/275988572-8a435cb0-69ce-48e4-a44d-95d68d07df59.png)
> ### Other
> 
> --
> ### Agreement
> 
>     * [x]  I have read the guidelines above and confirm I am following them with this report.

Skript-1.8 only supports 1.8.8

**Comment by TarikCoding** [comment]
One question, I know you are not the support from skQuery but can u help me with that it comes this error if not then not.

[22:37:37 INFO]: [SkQuery] Enabling SkQuery v4.1.10
[22:37:37 INFO]: [skQuery] Locating classes from SkQuery...
[22:37:37 INFO]: [skQuery] Beginning to process a total of 117 from SkQuery
[22:37:37 ERROR]: Error occurred while enabling SkQuery v4.1.10 (Is it up to date?)
java.lang.NoClassDefFoundError: org/bukkit/Particle
        at com.w00tmast3r.skquery.elements.SimpleTypes.run(SimpleTypes.java:28) ~[?:?]
        at com.w00tmast3r.skquery.Registration.register(Registration.java:149) ~[?:?]
        at com.w00tmast3r.skquery.Registration.enableSnooper(Registration.java:71) ~[?:?]
        at com.w00tmast3r.skquery.SkQuery.onEnable(SkQuery.java:37) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[spigot.jar:git-Spigot-21fe707-741a1bd]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340) [spigot.jar:git-Spigot-21fe707-741a1bd]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot.jar:git-Spigot-21fe707-741a1bd]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:357) [spigot.jar:git-Spigot-21fe707-741a1bd]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:317) [spigot.jar:git-Spigot-21fe707-741a1bd]
        at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:414) [spigot.jar:git-Spigot-21fe707-741a1bd]
        at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:378) [spigot.jar:git-Spigot-21fe707-741a1bd]
        at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:333) [spigot.jar:git-Spigot-21fe707-741a1bd]
        at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:263) [spigot.jar:git-Spigot-21fe707-741a1bd]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:525) [spigot.jar:git-Spigot-21fe707-741a1bd]
        at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.ClassNotFoundException: org.bukkit.Particle
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:91) ~[spigot.jar:git-Spigot-21fe707-741a1bd]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[spigot.jar:git-Spigot-21fe707-741a1bd]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:592) ~[?:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?]

**Comment by Matocolotoe** [comment]
Use the plugin provided in the #plugins channel on Discord
