### ISSUE TITLE
Velocity Vector bug

### ISSUE THREAD

**Issue by Chopnex** [Matocolotoe/Skript-1.8#87]
### Skript Version

[17:41:14 INFO]: [Skript] Skript's aliases can be found here: https://github.com/SkriptLang/skript-aliases
[17:41:14 INFO]: [Skript] Skript's documentation can be found here: https://docs.skriptlang.org/
[17:41:14 INFO]: [Skript] Skript's tutorials can be found here: https://docs.skriptlang.org/tutorials
[17:41:14 INFO]: [Skript] Server Version: git-PaperSpigot-94ac179e (MC: 1.8.8)
[17:41:14 INFO]: [Skript] Skript Version: 2.6.5-for-1.8
[17:41:14 INFO]: [Skript] Installed Skript Addons: 
[17:41:14 INFO]: [Skript]  - skript-placeholders v1.5.2 (https://github.com/APickledWalrus/skript-placeholders)
[17:41:14 INFO]: [Skript]  - skript-gui v1.3 (https://github.com/APickledWalrus/skript-gui)
[17:41:14 INFO]: [Skript]  - DiSky v4.12.1
[17:41:14 INFO]: [Skript]  - skDragon v0.17
[17:41:14 INFO]: [Skript]  - skript-reflect v2.3 (https://github.com/TPGamesNL/skript-reflect)
[17:41:14 INFO]: [Skript]  - skRayFall v1.9.25 (https://sk.rayfall.net/)
[17:41:14 INFO]: [Skript]  - SkQuery v4.1.6
[17:41:14 INFO]: [Skript]  - SkBee v1.10.3 (https://github.com/ShaneBeee/SkBee)
[17:41:14 INFO]: [Skript]  - WolvSK v1.7.2
[17:41:14 INFO]: [Skript] Installed dependencies: 
[17:41:14 INFO]: [Skript]  - Vault v1.7.3-CMI
[17:41:14 INFO]: [Skript]  - WorldGuard v6.1.3-SNAPSHOT;c904242

### Bug Description

Console spam when working with velocity vectors. Also seems like the player is not properly "pushed" in the right direction when using the .sk snippet below.

### Expected Behavior

No console error

### Steps to Reproduce

on fishing:
	if name of player's tool contains "Grappling Hook":
		if "%event.getState().name()%" = "IN_GROUND" or "FAILED_ATTEMPT":
			set {_loc} to location of event.getHook()
			if block below {_loc} != air: 
				set {_dif.x} to (x coordinate of {_loc}) - (x coordinate of player)
				set {_dif.z} to (z coordinate of {_loc}) - (z coordinate of player)
				set velocity of player to new Vector {_dif.x}, 1, {_dif.z}

### Errors or Screenshots

[17:40:02 WARN]: Excessive velocity set detected: tried to set velocity of entity #975 to (-0.12782011063308119,1.0,10.836626493827339).
[17:40:02 WARN]: java.lang.Exception: Stack trace
[17:40:02 WARN]:        at java.base/java.lang.Thread.dumpStack(Thread.java:1383)
[17:40:02 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.entity.CraftEntity.setVelocity(CraftEntity.java:213)
[17:40:02 WARN]:        at ch.njol.skript.expressions.ExprVelocity.change(ExprVelocity.java:83)
[17:40:02 WARN]:        at ch.njol.skript.effects.EffChange.execute(EffChange.java:282)
[17:40:02 WARN]:        at ch.njol.skript.lang.Effect.run(Effect.java:50)
[17:40:02 WARN]:        at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:61)
[17:40:02 WARN]:        at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:89)
[17:40:02 WARN]:        at ch.njol.skript.lang.Trigger.execute(Trigger.java:56)
[17:40:02 WARN]:        at ch.njol.skript.SkriptEventHandler.check(SkriptEventHandler.java:142)
[17:40:02 WARN]:        at ch.njol.skript.SkriptEventHandler.access$000(SkriptEventHandler.java:53)
[17:40:02 WARN]:        at ch.njol.skript.SkriptEventHandler$PriorityListener.lambda$new$0(SkriptEventHandler.java:71)
[17:40:02 WARN]:        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78)
[17:40:02 WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[17:40:02 WARN]:        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:517)
[17:40:02 WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:502)
[17:40:02 WARN]:        at net.minecraft.server.v1_8_R3.EntityFishingHook.l(EntityFishingHook.java:449)
[17:40:02 WARN]:        at net.minecraft.server.v1_8_R3.ItemFishingRod.a(ItemFishingRod.java:15)
[17:40:02 WARN]:        at net.minecraft.server.v1_8_R3.ItemStack.a(ItemStack.java:255)
[17:40:02 WARN]:        at net.minecraft.server.v1_8_R3.PlayerInteractManager.useItem(PlayerInteractManager.java:380)
[17:40:02 WARN]:        at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:739)
[17:40:02 WARN]:        at net.minecraft.server.v1_8_R3.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:52)
[17:40:02 WARN]:        at net.minecraft.server.v1_8_R3.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:1)
[17:40:02 WARN]:        at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13)
[17:40:02 WARN]:        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[17:40:02 WARN]:        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[17:40:02 WARN]:        at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44)
[17:40:02 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:883)
[17:40:02 WARN]:        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:368)
[17:40:02 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:818)
[17:40:02 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:654)
[17:40:02 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.lambda$0(MinecraftServer.java:135)
[17:40:02 WARN]:        at java.base/java.lang.Thread.run(Thread.java:829)

### Agreement

- [X] I have read the guidelines above and confirm I am following them with this report.

**Comment by Matocolotoe** [comment]
This is just a warning, and it looks like it comes from Paper.

**Comment by Chopnex** [comment]
Alright, you can probably close this then
